export const SELECTED = 'SELECTED';
export const MAIN_ITEMS_CHANGED = 'MAIN_ITEMS_CHANGED';
export const MAIN_SELECTED_ITEMS_CHANGED = 'MAIN_SELECTED_ITEMS_CHANGED';
export const UN_SELECTED_MAIN_ITEM = 'UN_SELECTED_MAIN_ITEM';

// improve view
export const SELECTED_IMPROVE_ITEM = 'SELECTED_IMPROVE_ITEM';
export const IMPROVE_SELECTED_ITEMS_CHANGED = 'IMPROVE_SELECTED_ITEMS_CHANGED';
export const UN_SELECTED_IMPROVE_ITEM = 'UN_SELECTED_IMPROVE_ITEM';
export const  ADD_NEW_ITEM = 'ADD_NEW_ITEM';
// secretShop
export const CHECK = 'CHECK';
