export const SELECTED = 'SELECTED';
export const DROP_MAIN_ITEM = 'DROP';

// improve view
export const IMPROVE_SELECTED_ITEMS_CHANGED = 'IMPROVE_SELECTED_ITEMS_CHANGED';
export const ADD_NEW_ITEM = 'ADD_NEW_ITEM';
export const DROP_IMPOVE_ITEM_SUCCSESS = 'DROP_IMPOVE_ITEM_SUCCSESS';
export const DROP_IMPOVES_ITEM = 'DROP_IMPOVES_ITEM';
// secretShop
export const CHECK = 'CHECK';
export const SUCCSESS_CRAFT_ITEM = 'SUCCSESS_CRAFT_ITEM';
export const DROP_SUCCSESS = 'DROP_SUCCSESS';
export const SELECTED_MAIN_ITEM = 'SELECTED_MAIN_ITEM';
